In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Netflix user data from the CSV file
data_path = 'data/netflix_users.csv'
df = pd.read_csv(data_path)
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [2]:
print("Dataset Information:")
df.info()
print("\n" + "="*50 + "\n")

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  object
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  object
 4   Subscription_Type  25000 non-null  object
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  object
 7   Last_Login         25000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.5+ MB

==================================================

In [3]:
print("Missing Values in Each Column:")
print(df.isnull().sum())
print("\n" + "="*50 + "\n")

Missing Values in Each Column:
User_ID              0
Name                 0
Age                  0
Country              0
Subscription_Type    0
Watch_Time_Hours     0
Favorite_Genre       0
Last_Login           0
dtype: int64

==================================================

In [4]:
print(f"Number of duplicate rows: {df.duplicated().sum()}")
print("\n" + "="*50 + "\n")

Number of duplicate rows: 0

==================================================

In [6]:
# Check for unique values in categorical columns to spot inconsistencies
unique_counts = df.nunique()

print("\nCount of Unique Values per Column:")
print(unique_counts)

Count of Unique Values per Column:
User_ID              25000
Name                   100
Age                     68
Country                 10
Subscription_Type        3
Watch_Time_Hours     22087
Favorite_Genre           7
Last_Login             366
dtype: int64

In [7]:
print(df['Name'].unique())

['James Martinez' 'John Miller' 'Emma Davis' 'Emma Miller' 'Jane Smith'
 'David Johnson' 'John Hernandez' 'Katie Hernandez' 'James Williams'
 'Alex Davis' 'Jane Miller' 'Jane Martinez' 'Alex Martinez' 'Alex Smith'
 'Michael Jones' 'Chris Miller' 'Chris Davis' 'Emma Williams'
 'Alex Johnson' 'John Jones' 'Michael Williams' 'Sarah Davis' 'John Smith'
 'Alex Brown' 'Chris Johnson' 'James Jones' 'Michael Johnson'
 'Sarah Smith' 'Chris Jones' 'John Williams' 'Jane Brown' 'David Davis'
 'Emma Hernandez' 'Sarah Williams' 'David Martinez' 'Emma Smith'
 'Sarah Hernandez' 'David Brown' 'Chris Garcia' 'John Johnson'
 'Sarah Garcia' 'Michael Brown' 'David Hernandez' 'Sarah Jones'
 'Alex Jones' 'Chris Martinez' 'Jane Garcia' 'Michael Martinez'
 'Chris Smith' 'Alex Hernandez' 'James Hernandez' 'Katie Martinez'
 'David Smith' 'James Davis' 'David Garcia' 'Alex Williams' 'Emma Brown'
 'Michael Davis' 'Emma Garcia' 'John Brown' 'Jane Davis' 'Michael Smith'
 'Emma Johnson' 'Katie Williams' 'Katie Jones' 'James Smith' 'David Jones'
 'James Garcia' 'Sarah Martinez' 'Sarah Brown' 'John Martinez'
 'Katie Miller' 'Sarah Miller' 'Katie Davis' 'Jane Williams' 'Emma Jones'
 'Chris Brown' 'John Davis' 'Jane Jones' 'Katie Brown' 'Alex Garcia'
 'David Miller' 'Katie Johnson' 'Chris Williams' 'Michael Garcia'
 'James Miller' 'Katie Smith' 'James Brown' 'Emma Martinez' 'John Garcia'
 'Chris Hernandez' 'Jane Johnson' 'Michael Miller' 'Sarah Johnson'
 'James Johnson' 'Jane Hernandez' 'Alex Miller' 'Katie Garcia'
 'Michael Hernandez' 'David Williams']

In [9]:
# Check for duplicate User_IDs
duplicate_user_ids = df[df.duplicated('User_ID', keep=False)]

if not duplicate_user_ids.empty:
    print("\nDuplicate User_IDs Found:")
    print(duplicate_user_ids)
else:
    print("\nNo duplicate User_IDs found. All users are unique.")

# A quicker way to just get the count
num_duplicates = df.duplicated('User_ID').sum()
print(f"\nTotal number of duplicate User_ID records: {num_duplicates}")

No duplicate User_IDs found. All users are unique.

Total number of duplicate User_ID records: 0

In [10]:
# Get the list of unique values for key categorical columns
print("\nUnique values in 'Country':")
print(df['Country'].unique())

print("\nUnique values in 'Subscription_Type':")
print(df['Subscription_Type'].unique())

print("\nUnique values in 'Favorite_Genre':")
print(df['Favorite_Genre'].unique())

Unique values in 'Country':
['France' 'USA' 'UK' 'Canada' 'Mexico' 'Japan' 'Australia' 'Germany'
 'Brazil' 'India']

Unique values in 'Subscription_Type':
['Premium' 'Basic' 'Standard']

Unique values in 'Favorite_Genre':
['Drama' 'Sci-Fi' 'Comedy' 'Documentary' 'Romance' 'Action' 'Horror']

In [13]:
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [ ]:

# --- Feature Engineering: Create the Target Variable 'Churn' ---
# A customer is considered 'churned' (1) if their last login was more than 30 days ago.
# We assume the data was pulled on '2023-11-05'.

# Ensure 'Last_Login' is in datetime format
df['Last_Login'] = pd.to_datetime(df['Last_Login'])

df['Churn'] = (data_pull_date - df['Last_Login']).dt.days > churn_threshold_days
df['Churn'] = df['Churn'].astype(int)

print("First 5 rows with the new 'Churn' column:")
print(df.head())
print("\nChurn Distribution:")
print(df['Churn'].value_counts())

KeyError: 'Last_Payment_Date'